### PR TITLE
New service account annotation feature.

### PR DESCRIPTION
**Pull request by xorl**
Added service account annotations to kubero to support modification of service accounts for RBAC on EKS and other platforms.

This is a WIP, works as intended, lack of Vue 3 experience has presented a bug in addition to adding serviceannotations, any help or contributions would be appreciated. When adding a new annotation the Object duplicates the field to a new form field because of the empty object/key.

### CODE REVIEW

**Comment by mms-gianni** [comment]
Nice ... I'll deep dive into it asap.

**Comment by xorl** [comment]
@mms-gianni I have updated the PR to use arrays after converting the object to an array to keep reactivity. It is now bug free and works as intended. Pushed the change and it is ready for official testing.

**Comment by xorl** [comment]
Had to update serviceaccount RBAC for the kuberorole. 

https://github.com/kubero-dev/kubero-operator/pull/31

**Comment by mms-gianni** [comment]
I plan to merge it into v2.1.0 soon

**Pull request merged**
