### PR TITLE
fix(api/gogs): better git uri parsing

### PR DESCRIPTION
**Pull request by m1m1x**
- removed the regex parsing in favor the git-parse-url lib in order to handle all git protocols

### CODE REVIEW

**Comment by m1m1x** [comment]
Hi,

I came accross this issue by testing Kubero with a Gogs git server.
Should you accept the change, I can update the other git modules before the final review.

**Comment by mms-gianni** [comment]
Looks cool. 

I'm currently using github. So I'm very happy someone using Gogs.

**Comment by mms-gianni** [comment]
@m1m1x This is a very good change. I've slightly adapted for typescript.

**Comment by m1m1x** [comment]
thanks :)

**Pull request merged**
