### PR TITLE
feat: adding option to select ingress class

### PR DESCRIPTION
**Pull request by cskiwi**
By default when creating a new app the ingress class is set to the environment value, or when that is not set to `nginx`.
this feature allows this to be loaded via the UI and default to the same behaviour

### CODE REVIEW

**Comment by mms-gianni** [comment]
I think you accidentally copied the app form to the pipelines folder.

**Comment by cskiwi** [comment]
@mms-gianni indeed, don't know how that happend. and I didn't get a notification of your comment. sorry for the late response

**Comment by cskiwi** [comment]
@mms-gianni FYI: updated the code changes to match the 2.4.0 release branch

**Comment by mms-gianni** [comment]
@cskiwi thx... looks great.

**Pull request merged**
